name: CSV Linter and Trailing Whitespaces

on:
  workflow_dispatch:

jobs:
  lint_and_check_trailing_whitespaces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install csvkit

    - name: Lint CSV files and check for errors
      run: |
        errors_found=false
        while IFS= read -r -d '' file; do
          echo "Checking $file"
          if csvclean -n --enable-all-checks "$file" 2>&1 | grep -q "Error:"; then
            echo "Errors found in $file"
            csvclean -n --enable-all-checks "$file"
            errors_found=true
          fi
        done < <(find . -name "*.csv" -print0)
        
        if [ "$errors_found" = true ]; then
          echo "Errors were found in one or more CSV files."
          exit 1
        else
          echo "No errors found in CSV files."
        fi

    - name: Check Trailing Whitespaces
      run: |
        trailing_spaces_found=false
        while IFS= read -r -d '' file; do
          if grep -q "[[:space:]]$" "$file"; then
            echo "ERROR: Found trailing whitespaces in $file"
            trailing_spaces_found=true
          fi
        done < <(find . -name "*.csv" -print0)
        
        if [ "$trailing_spaces_found" = true ]; then
          echo "Trailing whitespaces found in one or more CSV files."
          exit 1
        else
          echo "No trailing whitespaces found in CSV files."
        fi
