name: CSV Linter and Trailing Whitespaces

on:
  workflow_dispatch:

jobs:
  lint_and_check_trailing_whitespaces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install csvkit

    - name: Lint CSV files
      run: find . -name "*.csv" -exec csvlint -u 2 {} \\; > csvlint_output.txt 2>&1
      env:
        CI: true
    - name: Check for errors
      if: always()
      run: |
        if grep -v "No errors." csvclean_output.txt; then
          echo "Errors were found in one or more CSV files (possibly including quote issues):"
          cat csvclean_output.txt
          exit 1
        else
          echo "No errors found in CSV files."
        fi
    - name: Check Trailing Whitespaces
      run: |
        # Check if the special file contains any trailing whitespaces
        if grep -q "[[:space:]]$" ./prompts.csv; then
          echo "ERROR: Found trailing whitespaces in prompts.csv"
          exit 1
        else
          echo "No trailing whitespaces found in prompts.csv"
        fi
